### ISSUE TITLE
Errors when running tests

### ISSUE THREAD

**Issue by cscheeder** [baryshnikova-lab/safepy#6]
When I run the tests with 
```
python -m unittest discover -v -s tests/
```
I am getting errors related to 

> No such file or directory: '/Users/abaryshnikova/Lab/Datasets/safe-data/...' 

Despite changing the path variable in safe_default.ini file. 

Thanks,
Christian

**Comment by abarysh** [comment]
Thank you for letting us know. This should be fixed in commit [332fefb](https://github.com/baryshnikova-lab/safepy/commit/332fefbe093cac396bb3822f3d79a4c26b0e76aa) (pushed just now). The paths to files needed for the tests are now relative to the safe_data variable in safe_default.ini.

**Comment by cscheeder** [comment]
perfect, thanks!
