### ISSUE TITLE
SAFE on map wo/ edges 

### ISSUE THREAD

**Issue by cscheeder** [baryshnikova-lab/safepy#7]
I would like to reproduce the SAFE analysis on a map wo/ edges as shown in your recent preprint [https://www.biorxiv.org/content/10.1101/2022.12.22.521593v1](url). Yet this seems to not be straight forward and I was wondering whether I can somewhere find an exmaple/tutorial on this?

Thanks and best regards,
Christian

**Comment by abarysh** [comment]
Hi Christian,
The commit 842e4425715f651d18990b75cda392669d0d08af provides the functionality to load scatter plots and treat them as "networks". Example 3 (in the examples/ folder) shows how to use this functionality to annotate a UMAP plot with a single attribute. Using and combining multiple attributes (like in the case of Gene Ontology) should work the same as with regular networks. Let me know if you need any additional help in your specific case.
A.

**Comment by cscheeder** [comment]
Thanks a lot for adding the example. best, christian
